import { Kanji, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'সব (All)', name_jp: 'すべて' },
  { id: 'numbers', name: 'সংখ্যা (Numbers)', name_jp: '数字' },
  { id: 'time', name: 'সময় (Time)', name_jp: '時間' },
  { id: 'people', name: 'মানুষ (People)', name_jp: '人々' },
  { id: 'nature', name: 'প্রকৃতি (Nature)', name_jp: '自然' },
  { id: 'direction', name: 'দিক (Direction)', name_jp: '方角' },
  { id: 'action', name: 'ক্রিয়া (Action)', name_jp: '動作' },
  { id: 'adjectives', name: 'বিশেষণ (Adjectives)', name_jp: '形容詞' },
  { id: 'objects', name: 'বস্তু (Objects)', name_jp: '物' },
  { id: 'places', name: 'স্থান (Places)', name_jp: '場所' },
  { id: 'body', name: 'শরীর (Body)', name_jp: '体' },
];

export const KANJI_DATA: Kanji[] = [
  // Numbers
  { kanji: '一', onyomi: 'イチ', kunyomi: 'ひと', meaning_jp: 'ひとつ', meaning_en: 'One', meaning_bn: 'এক', strokes: 1, examples: ['一つ (ひとつ)', '一日 (いちにち)'], related: ['二', '三'], category: 'numbers' },
  { kanji: '二', onyomi: 'ニ', kunyomi: 'ふた', meaning_jp: 'ふたつ', meaning_en: 'Two', meaning_bn: 'দুই', strokes: 2, examples: ['二つ (ふたつ)', '二月 (にがつ)'], related: ['一', '三'], category: 'numbers' },
  { kanji: '三', onyomi: 'サン', kunyomi: 'み', meaning_jp: 'みっつ', meaning_en: 'Three', meaning_bn: 'তিন', strokes: 3, examples: ['三つ (みっつ)', '三月 (さんがつ)'], related: ['二', '四'], category: 'numbers' },
  { kanji: '四', onyomi: 'シ', kunyomi: 'よ、よん', meaning_jp: 'よっつ', meaning_en: 'Four', meaning_bn: 'চার', strokes: 5, examples: ['四つ (よっつ)', '四月 (しがつ)'], related: ['三', '五'], category: 'numbers' },
  { kanji: '五', onyomi: 'ゴ', kunyomi: 'いつ', meaning_jp: 'いつつ', meaning_en: 'Five', meaning_bn: 'পাঁচ', strokes: 4, examples: ['五つ (いつつ)', '五月 (ごがつ)'], related: ['四', '六'], category: 'numbers' },
  { kanji: '六', onyomi: 'ロク', kunyomi: 'む', meaning_jp: 'むっつ', meaning_en: 'Six', meaning_bn: 'ছয়', strokes: 4, examples: ['六つ (むっつ)', '六月 (ろくがつ)'], related: ['五', '七'], category: 'numbers' },
  { kanji: '七', onyomi: 'シチ', kunyomi: 'なな', meaning_jp: 'ななつ', meaning_en: 'Seven', meaning_bn: 'সাত', strokes: 2, examples: ['七つ (ななつ)', '七月 (しちがつ)'], related: ['六', '八'], category: 'numbers' },
  { kanji: '八', onyomi: 'ハチ', kunyomi: 'や', meaning_jp: 'やっつ', meaning_en: 'Eight', meaning_bn: 'আট', strokes: 2, examples: ['八つ (やっつ)', '八月 (はちがつ)'], related: ['七', '九'], category: 'numbers' },
  { kanji: '九', onyomi: 'キュウ、ク', kunyomi: 'ここの', meaning_jp: 'ここのつ', meaning_en: 'Nine', meaning_bn: 'নয়', strokes: 2, examples: ['九つ (ここのつ)', '九月 (くがつ)'], related: ['八', '十'], category: 'numbers' },
  { kanji: '十', onyomi: 'ジュウ', kunyomi: 'とお', meaning_jp: 'とお', meaning_en: 'Ten', meaning_bn: 'দশ', strokes: 2, examples: ['十 (じゅう)', '十月 (じゅうがつ)'], related: ['九', '百'], category: 'numbers' },
  { kanji: '百', onyomi: 'ヒャク', kunyomi: 'もも', meaning_jp: 'ひゃく', meaning_en: 'Hundred', meaning_bn: 'একশত', strokes: 6, examples: ['三百 (さんびゃく)', '百円 (ひゃくえん)'], related: ['十', '千'], category: 'numbers' },
  { kanji: '千', onyomi: 'セン', kunyomi: 'ち', meaning_jp: 'せん', meaning_en: 'Thousand', meaning_bn: 'এক হাজার', strokes: 3, examples: ['三千 (さんぜん)', '千葉 (ちば)'], related: ['百', '万'], category: 'numbers' },
  { kanji: '万', onyomi: 'マン', kunyomi: 'よろず', meaning_jp: 'まん', meaning_en: 'Ten thousand', meaning_bn: 'দশ হাজার', strokes: 3, examples: ['一万 (いちまん)', '万国 (ばんこく)'], related: ['千', '円'], category: 'numbers' },
  { kanji: '円', onyomi: 'エン', kunyomi: 'まる', meaning_jp: 'えん', meaning_en: 'Yen, Circle', meaning_bn: 'ইয়েন, বৃত্ত', strokes: 4, examples: ['百円 (ひゃくえん)', '円い (まるい)'], related: ['万'], category: 'objects' },

  // Time
  { kanji: '日', onyomi: 'ニチ、ジツ', kunyomi: 'ひ、か', meaning_jp: 'ひ', meaning_en: 'Day, Sun', meaning_bn: 'দিন, সূর্য', strokes: 4, examples: ['日曜日 (にちようび)', '今日 (きょう)'], related: ['月'], category: 'time' },
  { kanji: '月', onyomi: 'ゲツ、ガツ', kunyomi: 'つき', meaning_jp: 'つき', meaning_en: 'Month, Moon', meaning_bn: 'মাস, চাঁদ', strokes: 4, examples: ['月曜日 (げつようび)', '一月 (いちがつ)'], related: ['日'], category: 'time' },
  { kanji: '火', onyomi: 'カ', kunyomi: 'ひ', meaning_jp: 'ひ', meaning_en: 'Fire', meaning_bn: 'আগুন', strokes: 4, examples: ['火曜日 (かようび)', '花火 (はなび)'], related: ['水'], category: 'time' },
  { kanji: '水', onyomi: 'スイ', kunyomi: 'みず', meaning_jp: 'みず', meaning_en: 'Water', meaning_bn: 'পানি', strokes: 4, examples: ['水曜日 (すいようび)', '水 (みず)'], related: ['火'], category: 'time' },
  { kanji: '木', onyomi: 'モク', kunyomi: 'き', meaning_jp: 'き', meaning_en: 'Tree', meaning_bn: 'গাছ', strokes: 4, examples: ['木曜日 (もくようび)', '木 (き)'], related: ['林'], category: 'time' },
  { kanji: '金', onyomi: 'キン', kunyomi: 'かね', meaning_jp: 'かね', meaning_en: 'Gold, Money', meaning_bn: 'সোনা, টাকা', strokes: 8, examples: ['金曜日 (きんようび)', 'お金 (おかね)'], related: ['土'], category: 'time' },
  { kanji: '土', onyomi: 'ド', kunyomi: 'つち', meaning_jp: 'つち', meaning_en: 'Soil, Earth', meaning_bn: 'মাটি', strokes: 3, examples: ['土曜日 (どようび)', '土 (つち)'], related: ['金'], category: 'time' },
  { kanji: '年', onyomi: 'ネン', kunyomi: 'とし', meaning_jp: 'とし', meaning_en: 'Year', meaning_bn: 'বছর', strokes: 6, examples: ['来年 (らいねん)', '今年 (ことし)'], related: ['月'], category: 'time' },
  { kanji: '時', onyomi: 'ジ', kunyomi: 'とき', meaning_jp: 'とき', meaning_en: 'Time, Hour', meaning_bn: 'সময়', strokes: 10, examples: ['時間 (じかん)', '一時 (いちじ)'], related: ['分'], category: 'time' },
  { kanji: '分', onyomi: 'フン、ブン', kunyomi: 'わ.ける', meaning_jp: 'ふん', meaning_en: 'Minute, Part', meaning_bn: 'মিনিট, অংশ', strokes: 4, examples: ['五分 (ごふん)', '半分 (はんぶん)'], related: ['時'], category: 'time' },
  { kanji: '午', onyomi: 'ゴ', kunyomi: '', meaning_jp: 'ひる', meaning_en: 'Noon', meaning_bn: 'দুপুর', strokes: 4, examples: ['午前 (ごぜん)', '午後 (ごご)'], related: ['前', '後'], category: 'time' },
  { kanji: '今', onyomi: 'コン', kunyomi: 'いま', meaning_jp: 'いま', meaning_en: 'Now', meaning_bn: 'এখন', strokes: 4, examples: ['今 (いま)', '今月 (こんげつ)'], related: ['日'], category: 'time' },
  { kanji: '週', onyomi: 'シュウ', kunyomi: '', meaning_jp: 'しゅう', meaning_en: 'Week', meaning_bn: 'সপ্তাহ', strokes: 11, examples: ['先週 (せんしゅう)', '来週 (らいしゅう)'], related: ['年'], category: 'time' },
  { kanji: '間', onyomi: 'カン', kunyomi: 'あいだ', meaning_jp: 'あいだ', meaning_en: 'Interval, Between', meaning_bn: 'মধ্যবর্তী স্থান', strokes: 12, examples: ['時間 (じかん)', '間 (あいだ)'], related: ['時'], category: 'time' },

  // People
  { kanji: '人', onyomi: 'ジン、ニン', kunyomi: 'ひと', meaning_jp: 'ひと', meaning_en: 'Person', meaning_bn: 'মানুষ', strokes: 2, examples: ['日本人 (にほんじん)', '一人 (ひとり)'], related: ['男', '女'], category: 'people' },
  { kanji: '男', onyomi: 'ダン', kunyomi: 'おとこ', meaning_jp: 'おとこ', meaning_en: 'Man', meaning_bn: 'পুরুষ', strokes: 7, examples: ['男の子 (おとこのこ)', '男性 (だんせい)'], related: ['女'], category: 'people' },
  { kanji: '女', onyomi: 'ジョ', kunyomi: 'おんな', meaning_jp: 'おんな', meaning_en: 'Woman', meaning_bn: 'মহিলা', strokes: 3, examples: ['女の子 (おんなのこ)', '女性 (じょせい)'], related: ['男'], category: 'people' },
  { kanji: '子', onyomi: 'シ', kunyomi: 'こ', meaning_jp: 'こ', meaning_en: 'Child', meaning_bn: 'শিশু', strokes: 3, examples: ['子供 (こども)', '女子 (じょし)'], related: ['父', '母'], category: 'people' },
  { kanji: '父', onyomi: 'フ', kunyomi: 'ちち', meaning_jp: 'ちち', meaning_en: 'Father', meaning_bn: 'বাবা', strokes: 4, examples: ['父 (ちち)', 'お父さん (おとうさん)'], related: ['母'], category: 'people' },
  { kanji: '母', onyomi: 'ボ', kunyomi: 'はは', meaning_jp: 'はは', meaning_en: 'Mother', meaning_bn: 'মা', strokes: 5, examples: ['母 (はは)', 'お母さん (おかあさん)'], related: ['父'], category: 'people' },
  { kanji: '友', onyomi: 'ユウ', kunyomi: 'とも', meaning_jp: 'とも', meaning_en: 'Friend', meaning_bn: 'বন্ধু', strokes: 4, examples: ['友達 (ともだち)', '友人 (ゆうじん)'], related: ['人'], category: 'people' },

  // Directions
  { kanji: '上', onyomi: 'ジョウ', kunyomi: 'うえ', meaning_jp: 'うえ', meaning_en: 'Up, Above', meaning_bn: 'উপরে', strokes: 3, examples: ['上 (うえ)', '上手 (じょうず)'], related: ['下'], category: 'direction' },
  { kanji: '下', onyomi: 'カ、ゲ', kunyomi: 'した', meaning_jp: 'した', meaning_en: 'Down, Below', meaning_bn: 'নিচে', strokes: 3, examples: ['下 (した)', '地下鉄 (ちかてつ)'], related: ['上'], category: 'direction' },
  { kanji: '左', onyomi: 'サ', kunyomi: 'ひだり', meaning_jp: 'ひだり', meaning_en: 'Left', meaning_bn: 'বাম', strokes: 5, examples: ['左 (ひだり)', '左手 (ひだりて)'], related: ['右'], category: 'direction' },
  { kanji: '右', onyomi: 'ウ', kunyomi: 'みぎ', meaning_jp: 'みぎ', meaning_en: 'Right', meaning_bn: 'ডান', strokes: 5, examples: ['右 (みぎ)', '右手 (みぎて)'], related: ['左'], category: 'direction' },
  { kanji: '中', onyomi: 'チュウ', kunyomi: 'なか', meaning_jp: 'なか', meaning_en: 'Inside, Middle', meaning_bn: 'মাঝখানে', strokes: 4, examples: ['中 (なか)', '中国 (ちゅうごく)'], related: ['外'], category: 'direction' },
  { kanji: '外', onyomi: 'ガイ', kunyomi: 'そと', meaning_jp: 'そと', meaning_en: 'Outside', meaning_bn: 'বাইরে', strokes: 5, examples: ['外 (そと)', '外国 (がいこく)'], related: ['中'], category: 'direction' },
  { kanji: '前', onyomi: 'ゼン', kunyomi: 'まえ', meaning_jp: 'まえ', meaning_en: 'Before, Front', meaning_bn: 'সামনে', strokes: 9, examples: ['前 (まえ)', '午前 (ごぜん)'], related: ['後'], category: 'direction' },
  { kanji: '後', onyomi: 'ゴ、コウ', kunyomi: 'うしろ、あと', meaning_jp: 'うしろ', meaning_en: 'After, Back', meaning_bn: 'পিছনে', strokes: 9, examples: ['後ろ (うしろ)', '午後 (ごご)'], related: ['前'], category: 'direction' },
  { kanji: '東', onyomi: 'トウ', kunyomi: 'ひがし', meaning_jp: 'ひがし', meaning_en: 'East', meaning_bn: 'পূর্ব', strokes: 8, examples: ['東 (ひがし)', '東京 (とうきょう)'], related: ['西'], category: 'direction' },
  { kanji: '西', onyomi: 'セイ、サイ', kunyomi: 'にし', meaning_jp: 'にし', meaning_en: 'West', meaning_bn: 'পশ্চিম', strokes: 6, examples: ['西 (にし)', '西洋 (せいよう)'], related: ['東'], category: 'direction' },
  { kanji: '南', onyomi: 'ナン', kunyomi: 'みなみ', meaning_jp: 'みなみ', meaning_en: 'South', meaning_bn: 'দক্ষিণ', strokes: 9, examples: ['南 (みなみ)', '東南アジア'], related: ['北'], category: 'direction' },
  { kanji: '北', onyomi: 'ホク', kunyomi: 'きた', meaning_jp: 'きた', meaning_en: 'North', meaning_bn: 'উত্তর', strokes: 5, examples: ['北 (きた)', '北海道 (ほっかいどう)'], related: ['南'], category: 'direction' },

  // Nature
  { kanji: '山', onyomi: 'サン', kunyomi: 'やま', meaning_jp: 'やま', meaning_en: 'Mountain', meaning_bn: 'পাহাড়', strokes: 3, examples: ['山 (やま)', '富士山 (ふじさん)'], related: ['川'], category: 'nature' },
  { kanji: '川', onyomi: 'セン', kunyomi: 'かわ', meaning_jp: 'かわ', meaning_en: 'River', meaning_bn: 'নদী', strokes: 3, examples: ['川 (かわ)', 'ナイル川 (ないるがわ)'], related: ['山'], category: 'nature' },
  { kanji: '空', onyomi: 'クウ', kunyomi: 'そら', meaning_jp: 'そら', meaning_en: 'Sky, Empty', meaning_bn: 'আকাশ', strokes: 8, examples: ['空 (そら)', '空港 (くうこう)'], related: ['天'], category: 'nature' },
  { kanji: '天', onyomi: 'テン', kunyomi: 'あま', meaning_jp: 'てん', meaning_en: 'Heaven', meaning_bn: 'স্বর্গ', strokes: 4, examples: ['天気 (てんき)', '天国 (てんごく)'], related: ['空'], category: 'nature' },
  { kanji: '気', onyomi: 'キ', kunyomi: '', meaning_jp: 'き', meaning_en: 'Spirit, Air', meaning_bn: 'বাতাস, মন', strokes: 6, examples: ['元気 (げんき)', '天気 (てんき)'], related: ['天'], category: 'nature' },
  { kanji: '雨', onyomi: 'ウ', kunyomi: 'あめ', meaning_jp: 'あめ', meaning_en: 'Rain', meaning_bn: 'বৃষ্টি', strokes: 8, examples: ['雨 (あめ)', '大雨 (おおあめ)'], related: ['雪'], category: 'nature' },
  { kanji: '花', onyomi: 'カ', kunyomi: 'はな', meaning_jp: 'はな', meaning_en: 'Flower', meaning_bn: 'ফুল', strokes: 7, examples: ['花 (はな)', '花火 (はなび)'], related: ['木'], category: 'nature' },

  // Actions
  { kanji: '見', onyomi: 'ケン', kunyomi: 'み.る', meaning_jp: 'みる', meaning_en: 'To See', meaning_bn: 'দেখা', strokes: 7, examples: ['見る (みる)', '見物 (けんぶつ)'], related: ['聞'], category: 'action' },
  { kanji: '行', onyomi: 'コウ', kunyomi: 'い.く', meaning_jp: 'いく', meaning_en: 'To Go', meaning_bn: 'যাওয়া', strokes: 6, examples: ['行く (いく)', '旅行 (りょこう)'], related: ['来'], category: 'action' },
  { kanji: '来', onyomi: 'ライ', kunyomi: 'く.る', meaning_jp: 'くる', meaning_en: 'To Come', meaning_bn: 'আসা', strokes: 7, examples: ['来る (くる)', '来年 (らいねん)'], related: ['行'], category: 'action' },
  { kanji: '食', onyomi: 'ショク', kunyomi: 'た.べる', meaning_jp: 'たべる', meaning_en: 'To Eat', meaning_bn: 'খাওয়া', strokes: 9, examples: ['食べる (たべる)', '食事 (しょくじ)'], related: ['飲'], category: 'action' },
  { kanji: '飲', onyomi: 'イン', kunyomi: 'の.む', meaning_jp: 'のむ', meaning_en: 'To Drink', meaning_bn: 'পান করা', strokes: 12, examples: ['飲む (のむ)', '飲み物 (のみもの)'], related: ['食'], category: 'action' },
  { kanji: '読', onyomi: 'ドク', kunyomi: 'よ.む', meaning_jp: 'よむ', meaning_en: 'To Read', meaning_bn: 'পড়া', strokes: 14, examples: ['読む (よむ)', '読書 (どくしょ)'], related: ['書'], category: 'action' },
  { kanji: '書', onyomi: 'ショ', kunyomi: 'か.く', meaning_jp: 'かく', meaning_en: 'To Write', meaning_bn: 'লেখা', strokes: 10, examples: ['書く (かく)', '図書館 (としょかん)'], related: ['読'], category: 'action' },
  { kanji: '話', onyomi: 'ワ', kunyomi: 'はな.す', meaning_jp: 'はなす', meaning_en: 'To Speak', meaning_bn: 'কথা বলা', strokes: 13, examples: ['話す (はなす)', '電話 (でんわ)'], related: ['言'], category: 'action' },
  { kanji: '買', onyomi: 'バイ', kunyomi: 'か.う', meaning_jp: 'かう', meaning_en: 'To Buy', meaning_bn: 'কেনা', strokes: 12, examples: ['買う (かう)', '買い物 (かいもの)'], related: ['売'], category: 'action' },
  { kanji: '聞', onyomi: 'ブン', kunyomi: 'き.く', meaning_jp: 'きく', meaning_en: 'To Listen', meaning_bn: 'শোনা', strokes: 14, examples: ['聞く (きく)', '新聞 (しんぶん)'], related: ['見'], category: 'action' },
  { kanji: '立', onyomi: 'リツ', kunyomi: 'た.つ', meaning_jp: 'たつ', meaning_en: 'To Stand', meaning_bn: 'দাঁড়ানো', strokes: 5, examples: ['立つ (たつ)', '国立 (こくりつ)'], related: ['休'], category: 'action' },
  { kanji: '休', onyomi: 'キュウ', kunyomi: 'やす.む', meaning_jp: 'やすむ', meaning_en: 'To Rest', meaning_bn: 'বিশ্রাম করা', strokes: 6, examples: ['休む (やすむ)', '休日 (きゅうじつ)'], related: ['立'], category: 'action' },
  { kanji: '出', onyomi: 'シュツ', kunyomi: 'で.る', meaning_jp: 'でる', meaning_en: 'To Exit', meaning_bn: 'বের হওয়া', strokes: 5, examples: ['出る (でる)', '出口 (でぐち)'], related: ['入'], category: 'action' },
  { kanji: '入', onyomi: 'ニュウ', kunyomi: 'はい.る', meaning_jp: 'はいる', meaning_en: 'To Enter', meaning_bn: 'প্রবেশ করা', strokes: 2, examples: ['入る (はいる)', '入口 (いりぐち)'], related: ['出'], category: 'action' },

  // Adjectives
  { kanji: '大', onyomi: 'ダイ', kunyomi: 'おお.きい', meaning_jp: 'おおきい', meaning_en: 'Big', meaning_bn: 'বড়', strokes: 3, examples: ['大きい (おおきい)', '大学 (だいがく)'], related: ['小'], category: 'adjectives' },
  { kanji: '小', onyomi: 'ショウ', kunyomi: 'ちい.さい', meaning_jp: 'ちいさい', meaning_en: 'Small', meaning_bn: 'ছোট', strokes: 3, examples: ['小さい (ちいさい)', '小学校 (しょうがっこう)'], related: ['大'], category: 'adjectives' },
  { kanji: '高', onyomi: 'コウ', kunyomi: 'たか.い', meaning_jp: 'たかい', meaning_en: 'High, Expensive', meaning_bn: 'উঁচু, দামি', strokes: 10, examples: ['高い (たかい)', '高校 (こうこう)'], related: ['安'], category: 'adjectives' },
  { kanji: '安', onyomi: 'アン', kunyomi: 'やす.い', meaning_jp: 'やすい', meaning_en: 'Cheap, Safe', meaning_bn: 'সস্তা, নিরাপদ', strokes: 6, examples: ['安い (やすい)', '安心 (あんしん)'], related: ['高'], category: 'adjectives' },
  { kanji: '新', onyomi: 'シン', kunyomi: 'あたら.しい', meaning_jp: 'あたらしい', meaning_en: 'New', meaning_bn: 'নতুন', strokes: 13, examples: ['新しい (あたらしい)', '新聞 (しんぶん)'], related: ['古'], category: 'adjectives' },
  { kanji: '古', onyomi: 'コ', kunyomi: 'ふる.い', meaning_jp: 'ふるい', meaning_en: 'Old', meaning_bn: 'পুরাতন', strokes: 5, examples: ['古い (ふるい)', '中古 (ちゅうこ)'], related: ['新'], category: 'adjectives' },
  { kanji: '長', onyomi: 'チョウ', kunyomi: 'なが.い', meaning_jp: 'ながい', meaning_en: 'Long', meaning_bn: 'লম্বা', strokes: 8, examples: ['長い (ながい)', '校長 (こうちょう)'], related: ['短'], category: 'adjectives' },
  { kanji: '多', onyomi: 'タ', kunyomi: 'おお.い', meaning_jp: 'おおい', meaning_en: 'Many', meaning_bn: 'অনেক', strokes: 6, examples: ['多い (おおい)', '多少 (たしょう)'], related: ['少'], category: 'adjectives' },
  { kanji: '少', onyomi: 'ショウ', kunyomi: 'すく.ない', meaning_jp: 'すくない', meaning_en: 'Few', meaning_bn: 'অল্প', strokes: 4, examples: ['少し (すこし)', '少年 (しょうねん)'], related: ['多'], category: 'adjectives' },
  { kanji: '白', onyomi: 'ハク', kunyomi: 'しろ', meaning_jp: 'しろ', meaning_en: 'White', meaning_bn: 'সাদা', strokes: 5, examples: ['白い (しろい)', '白人 (はくじん)'], related: ['黒'], category: 'adjectives' },

  // Objects/Places/Body
  { kanji: '本', onyomi: 'ホン', kunyomi: 'もと', meaning_jp: 'ほん', meaning_en: 'Book, Origin', meaning_bn: 'বই', strokes: 5, examples: ['本 (ほん)', '日本 (にほん)'], related: ['木'], category: 'objects' },
  { kanji: '車', onyomi: 'シャ', kunyomi: 'くるま', meaning_jp: 'くるま', meaning_en: 'Car', meaning_bn: 'গাড়ি', strokes: 7, examples: ['車 (くるま)', '電車 (でんしゃ)'], related: ['電'], category: 'objects' },
  { kanji: '名', onyomi: 'メイ', kunyomi: 'な', meaning_jp: 'な', meaning_en: 'Name', meaning_bn: 'নাম', strokes: 6, examples: ['名前 (なまえ)', '有名な (ゆうめいな)'], related: ['人'], category: 'objects' },
  { kanji: '電', onyomi: 'デン', kunyomi: '', meaning_jp: 'でん', meaning_en: 'Electricity', meaning_bn: 'বিদ্যুৎ', strokes: 13, examples: ['電気 (でんき)', '電車 (でんしゃ)'], related: ['車'], category: 'objects' },
  { kanji: '校', onyomi: 'コウ', kunyomi: '', meaning_jp: 'こう', meaning_en: 'School', meaning_bn: 'স্কুল', strokes: 10, examples: ['学校 (がっこう)', '高校 (こうこう)'], related: ['学'], category: 'places' },
  { kanji: '店', onyomi: 'テン', kunyomi: 'みせ', meaning_jp: 'みせ', meaning_en: 'Shop', meaning_bn: 'দোকান', strokes: 8, examples: ['店 (みせ)', '店員 (てんいん)'], related: ['買'], category: 'places' },
  { kanji: '国', onyomi: 'コク', kunyomi: 'くに', meaning_jp: 'くに', meaning_en: 'Country', meaning_bn: 'দেশ', strokes: 8, examples: ['国 (くに)', '外国 (がいこく)'], related: ['外'], category: 'places' },
  { kanji: '道', onyomi: 'ドウ', kunyomi: 'みち', meaning_jp: 'みち', meaning_en: 'Road, Way', meaning_bn: 'রাস্তা', strokes: 12, examples: ['道 (みち)', '書道 (しょどう)'], related: ['車'], category: 'places' },
  { kanji: '駅', onyomi: 'エキ', kunyomi: '', meaning_jp: 'えき', meaning_en: 'Station', meaning_bn: 'স্টেশন', strokes: 14, examples: ['駅 (えき)', '駅長 (えきちょう)'], related: ['電'], category: 'places' },
  { kanji: '手', onyomi: 'シュ', kunyomi: 'て', meaning_jp: 'て', meaning_en: 'Hand', meaning_bn: 'হাত', strokes: 4, examples: ['手 (て)', '上手 (じょうず)'], related: ['足'], category: 'body' },
  { kanji: '足', onyomi: 'ソク', kunyomi: 'あし', meaning_jp: 'あし', meaning_en: 'Foot, Leg', meaning_bn: 'পা', strokes: 7, examples: ['足 (あし)', '足りる (たりる)'], related: ['手'], category: 'body' },
  { kanji: '目', onyomi: 'モク', kunyomi: 'め', meaning_jp: 'め', meaning_en: 'Eye', meaning_bn: 'চোখ', strokes: 5, examples: ['目 (め)', '目的 (もくてき)'], related: ['口'], category: 'body' },
  { kanji: '口', onyomi: 'コウ', kunyomi: 'くち', meaning_jp: 'くち', meaning_en: 'Mouth', meaning_bn: 'মুখ', strokes: 3, examples: ['口 (くち)', '入口 (いりぐち)'], related: ['耳'], category: 'body' },
  { kanji: '耳', onyomi: 'ジ', kunyomi: 'みみ', meaning_jp: 'みみ', meaning_en: 'Ear', meaning_bn: 'কান', strokes: 6, examples: ['耳 (みみ)'], related: ['目'], category: 'body' }
];